apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "dbg-okteto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 888
      targetPort: 888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dbg-app
    app.kubernetes.io/instance: {{ .Release.Name }}
